import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('button', { name: 'New' }).click();
  await expect(page.locator('form').filter({ hasText: 'Date of ArrivalDate of DepartureRoom Sizesingle-roomdouble-roombusiness-' })).toBeVisible();
  await page.locator('div').filter({ hasText: /^Delete$/ }).click();
  await expect(page.locator('form').filter({ hasText: 'Date of ArrivalDate of DepartureRoom Sizesingle-roomdouble-roombusiness-' })).toBeVisible();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('test');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('test last name');
  await page.getByRole('textbox', { name: 'E-Mail' }).click();
  await page.getByRole('textbox', { name: 'E-Mail' }).fill('test@test');
  await page.getByRole('spinbutton', { name: 'Phone Number' }).click();
  await page.getByRole('spinbutton', { name: 'Phone Number' }).fill('123456');
  await page.getByLabel('Street Name').click();
  await page.getByLabel('Street Name').fill('test');
  await page.locator('div').filter({ hasText: /^Street Number$/ }).nth(1).click();
  await page.getByLabel('Street Number').fill('6');
  await page.locator('div').filter({ hasText: /^ZIP$/ }).nth(1).click();
  await page.getByLabel('ZIP').fill('1234');
  await page.getByLabel('State').click();
  await page.getByRole('option', { name: 'Arizona' }).click();
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('TEST');
  await page.getByLabel('Open').click();
  await page.getByRole('option', { name: 'extraWiFi' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('grid')).toContainText('1–3 of 3');
  await expect(page.getByRole('grid')).toContainText('test last name');
  await page.getByText('test last name').click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('updated last name');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('update');
  await page.getByRole('textbox', { name: 'E-Mail' }).click();
  await page.getByRole('textbox', { name: 'E-Mail' }).fill('updated email');
  await page.getByLabel('I confirm the information').check();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('grid')).toContainText('1–3 of 3');
  await expect(page.getByRole('grid')).toContainText('updated last name');
  await expect(page.getByRole('grid')).toContainText('update');
  await expect(page.getByRole('grid')).toContainText('updated email');
  await page.getByText('updated last name').click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await expect(page.getByRole('grid')).toContainText('1–2 of 2');
  await page.getByLabel('E-Mail').click();
  await page.getByLabel('E-Mail').fill('updated email');
  await expect(page.getByRole('grid')).toContainText('0–0 of 0');
});