name: Merge to Main and Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda Functions
      run: |
        cd aws-backend/lambda-functions
        for file in *.js; do
          if [[ -f $file ]] && [[ $file != *.test.js ]]; then
            FUNCTION_NAME="${file%.*}"
            zip -r ${FUNCTION_NAME}.zip $file
            aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://${FUNCTION_NAME}.zip
          fi
        done

    - name: Deploy Frontend to S3
      run: |
        cd hotel-reservation
        npm run build
        aws s3 sync build/ s3://yujie-wu-reservation-website
