name: Test Workflow

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hotel-reservation

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install Frontend Dependencies
      run: npm install

    - name: ESLint Check (Frontend)
      run: npm run lint

    - name: Run Jest Tests (Frontend)
      run: npm test

  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws-backend

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install Backend Dependencies
      run: npm install

    - name: ESLint Check (Backend)
      run: npm run lint

    - name: Compile TypeScript to JavaScript (Backend)
      run: npm run build

    - name: Run Jest Tests (Backend)
      run: npm test

  playwright-e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3

    - name: Install Playwright Dependencies
      run: npm install

    - name: Install Browser
      run: npx playwright install

    - name: Install dependencies for hotel-reservation
      run: |
        cd hotel-reservation
        npm install

    - name: Start Application in Background
      run: |
        cd hotel-reservation
        nohup npm start &

    - name: Wait for Application to be Ready
      run: |
        wget --retry-connrefused --no-check-certificate -T 30 http://localhost:3000

    - name: Run Playwright tests
      run: npm run test

  create-pull-request:
    runs-on: ubuntu-latest
    needs: [ frontend-tests, backend-tests, playwright-e2e-tests ]
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update integration'
          title: 'Auto PR from CI'
          body: 'This is an auto-generated PR from CI'
          branch: 'auto-pr-${{ github.run_number }}'
          base: 'main'
